"""Repair UTF-8 → Windows-1252 → UTF-8 mojibake in machine-package JSON files.

A bug somewhere in the authoring pipeline let a UTF-8 string be decoded as
Windows-1252 and then re-saved as UTF-8. Result: an em-dash (—, U+2014, UTF-8
bytes E2 80 94) becomes the three characters â € " (U+00E2 U+20AC U+2014). This
script finds those round-trip survivors and rewrites them to their original form.

Usage:
    python Tools/fix_mojibake.py                        # dry-run, show diffs
    python Tools/fix_mojibake.py --apply                # write fixes in place

Scope: every *.json beneath Assets/_Project/Data/Packages/. The StreamingAssets
copies are regenerated by the build pipeline, so we don't touch them.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGES_DIR = REPO_ROOT / "Assets" / "_Project" / "Data" / "Packages"


def repair(text: str) -> str:
    """Round-trip the bytes back. If the string has no mojibake, this is a no-op."""
    try:
        return text.encode("windows-1252").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text


def walk_strings(node, repair_fn):
    """Recursively repair every string leaf. Returns (new_node, changed_count)."""
    if isinstance(node, str):
        fixed = repair_fn(node)
        return fixed, (1 if fixed != node else 0)
    if isinstance(node, list):
        out, total = [], 0
        for item in node:
            new_item, n = walk_strings(item, repair_fn)
            out.append(new_item)
            total += n
        return out, total
    if isinstance(node, dict):
        out, total = {}, 0
        for k, v in node.items():
            new_v, n = walk_strings(v, repair_fn)
            out[k] = new_v
            total += n
        return out, total
    return node, 0


def process_file(path: Path, apply: bool) -> int:
    raw = path.read_text(encoding="utf-8")
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"  [skip] {path}: invalid JSON ({exc})")
        return 0

    fixed, changed = walk_strings(data, repair)
    if changed == 0:
        return 0

    rel = path.relative_to(REPO_ROOT)
    print(f"  {rel}: {changed} string(s) repaired")
    if apply:
        # Preserve the existing UTF-8 + 2-space indent style most package JSONs use.
        path.write_text(
            json.dumps(fixed, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Write fixes (otherwise dry-run).")
    args = parser.parse_args()

    if not PACKAGES_DIR.is_dir():
        print(f"Packages dir not found: {PACKAGES_DIR}", file=sys.stderr)
        return 2

    # Skip .pose_backups/ snapshots and Blender/gltfpack reports — runtime never reads them
    # and rewriting them just inflates the diff with dead state.
    def is_skipped(p: Path) -> bool:
        parts = set(p.parts)
        if any(seg.startswith(".") for seg in p.parts):
            return True
        return p.name.endswith(".gltfpack_report.json")

    json_files = sorted(p for p in PACKAGES_DIR.rglob("*.json") if not is_skipped(p))
    print(f"Scanning {len(json_files)} JSON files under {PACKAGES_DIR.relative_to(REPO_ROOT)}")
    if not args.apply:
        print("(dry-run — re-run with --apply to write changes)\n")
    else:
        print("(applying fixes)\n")

    total = sum(process_file(p, args.apply) for p in json_files)
    print(f"\nTotal repaired strings: {total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
